# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIdes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 140, 381, 291))
        self.groupBox.setObjectName("groupBox")

        self.lineEdit_kg = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_kg.setGeometry(QtCore.QRect(30, 30, 113, 20))
        self.lineEdit_kg.setObjectName("lineEdit_kg")
        self.lineEdit_kn = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_kn.setGeometry(QtCore.QRect(30, 60, 113, 20))
        self.lineEdit_kn.setObjectName("lineEdit_kn")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))